In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### 1. Import the data and make the same changes to the data you made in exercise 8.

In [2]:
df = pd.read_excel('../W13/framingham_dataset_mod.xlsx')
display(df)
df = df.dropna()

id  sex  sbp  dbp    scl  age   bmi  month  chdfate
0     2642    1  120   80  267.0   55  25.0      8        1
1     4627    1  130   78  192.0   53  28.4     12        1
2     2568    1  144   90  207.0   61  25.1      8        1
3     4192    1   92   66  231.0   48  26.2     11        1
4     3977    1  162   98  271.0   39  28.4     11        1
...    ...  ...  ...  ...    ...  ...   ...    ...      ...
4690  1805    2  130   84  175.0   35  27.7      4        0
4691  1976    2  136   92  197.0   45  23.1      5        0
4692  3195    1  130   88  213.0   47  28.4      9        0
4693  1674    2  112   68  252.0   40  22.0      4        0
4694  4526    1  112   76  177.0   40  23.5     12        0

[4695 rows x 9 columns]

In [3]:
df['winter'] = np.where((df.month == 12) | (df.month < 3), 1, 0)
df['spring'] = np.where((df.month > 3) & (df.month < 6), 1, 0)
df['summer'] = np.where((df.month > 5) & (df.month < 9), 1, 0)
df['fall'] = np.where((df.month > 8) & (df.month < 12), 1, 0)
display(df)

id  sex  sbp  dbp    scl  age   bmi  month  chdfate  winter  spring  \
0     2642    1  120   80  267.0   55  25.0      8        1       0       0   
1     4627    1  130   78  192.0   53  28.4     12        1       1       0   
2     2568    1  144   90  207.0   61  25.1      8        1       0       0   
3     4192    1   92   66  231.0   48  26.2     11        1       0       0   
4     3977    1  162   98  271.0   39  28.4     11        1       0       0   
...    ...  ...  ...  ...    ...  ...   ...    ...      ...     ...     ...   
4690  1805    2  130   84  175.0   35  27.7      4        0       0       1   
4691  1976    2  136   92  197.0   45  23.1      5        0       0       1   
4692  3195    1  130   88  213.0   47  28.4      9        0       0       0   
4693  1674    2  112   68  252.0   40  22.0      4        0       0       1   
4694  4526    1  112   76  177.0   40  23.5     12        0       1       0   

      summer  fall  
0          1     0  
1          0     0  
2          1     0  
3          0     1  
4          0     1  
...      ...   ...  
4690       0     0  
4691       0     0  
4692       0     1  
4693       0     0  
4694       0     0  

[4654 rows x 13 columns]

### 2. Split the data into a training test split. Use an 80% training and 20% test set split.

In [4]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size = 0.2, random_state = 0)
#X_train = train[['sex', 'sbp', 'dbp', 'scl', 'age', 'bmi', 'spring', 'summer', 'fall']]
#X_test = test[['sex', 'sbp', 'dbp', 'scl', 'age', 'bmi', 'spring', 'summer', 'fall']]
y_train = train['chdfate']
y_test = test['chdfate']

### 3. Scale the predictor variables

In [5]:
from sklearn.preprocessing import StandardScaler
X_train = StandardScaler().fit_transform(train[['sex', 'sbp', 'dbp', 'scl', 'age', 'bmi', 'spring', 'summer', 'fall']])
X_test = StandardScaler().fit_transform(test[['sex', 'sbp', 'dbp', 'scl', 'age', 'bmi', 'spring', 'summer', 'fall']])

### 4. Fit a logistic regression model on the training data using all the relevant predictor variables (Note: use season, not month. Also, ID is not a predictor variable. Do not use it). Use sklearn. 

In [6]:
from sklearn.linear_model import LogisticRegression

# initialize model
model_logit = LogisticRegression(random_state = 0)
# train model
model_logit.fit(X_train, y_train)
# make prediction on the test set
y_pred_1 = model_logit.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix
cm_logit = confusion_matrix(y_test, y_pred_1)
print ("Confusion Matrix : \n", cm_logit)

Confusion Matrix : 
 [[584  45]
 [245  57]]


### 5. Using the test data, generate a confusion matrix and evaluate the logistic regression model
**a. Accuracy**

In [8]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print ("Accuracy : ", accuracy_score(y_test, y_pred_1),
      "\nPrecision : ", precision_score(y_test, y_pred_1),
      "\nRecall : ", recall_score(y_test, y_pred_1))

Accuracy :  0.6885069817400644 
Precision :  0.5588235294117647 
Recall :  0.18874172185430463


### 6. Fit a neural net classifier model using the defaults

In [9]:
from sklearn.neural_network import MLPClassifier
model_neural_default = MLPClassifier(random_state=1) # MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
model_neural_default.fit(X_train, y_train)

y_pred_2 = model_neural_default.predict(X_test)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


### 7. Generate a confusion matrix and evaluate the neural net model
a. Accuracy
b. Precision
c. Recall

In [10]:
cm = confusion_matrix(y_test, y_pred_2)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[571  58]
 [241  61]]


In [11]:
print ("Accuracy : ", accuracy_score(y_test, y_pred_2),
      "\nPrecision : ", precision_score(y_test, y_pred_2),
      "\nRecall : ", recall_score(y_test, y_pred_2))

Accuracy :  0.6788399570354458 
Precision :  0.5126050420168067 
Recall :  0.20198675496688742


### 8. Fit a neural net classifier model using 24 neurons and 2 hidden layers

In [12]:
model_neural_2 = MLPClassifier(hidden_layer_sizes=(24, 2), random_state=1)
model_neural_2.fit(X_train, y_train)

y_pred_3 = model_neural_2.predict(X_test)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


### 9. Generate a confusion matrix and evaluate the new neural net model
a. Accuracy
b. Precision
c. Recall

In [13]:
cm_3 = confusion_matrix(y_test, y_pred_3)
print ("Confusion Matrix : \n", cm_3)

Confusion Matrix : 
 [[567  62]
 [233  69]]


In [14]:
print ("Accuracy : ", accuracy_score(y_test, y_pred_3),
      "\nPrecision : ", precision_score(y_test, y_pred_3),
      "\nRecall : ", recall_score(y_test, y_pred_3))

Accuracy :  0.6831364124597207 
Precision :  0.5267175572519084 
Recall :  0.22847682119205298


### 10. Compare performance of all 3 models

In [15]:
performance = pd.DataFrame({"Accuracy" : [accuracy_score(y_test, y_pred_1), accuracy_score(y_test, y_pred_2), accuracy_score(y_test, y_pred_3)],
                            "Precision" : [precision_score(y_test, y_pred_1), precision_score(y_test, y_pred_2), precision_score(y_test, y_pred_3)],
                            "Recall" : [recall_score(y_test, y_pred_1), recall_score(y_test, y_pred_2), recall_score(y_test, y_pred_3)],
                           "Model" : ["Logistic Regression", "Default Neural Net", "Neural Net"]})
performance.set_index("Model", inplace = True)
performance

Accuracy  Precision    Recall
Model                                             
Logistic Regression  0.688507   0.558824  0.188742
Default Neural Net   0.678840   0.512605  0.201987
Neural Net           0.683136   0.526718  0.228477

*While the three models all perform relatively bad, logistic regression has the best accuracy and precision, but the lowest recall. In terms of all three scales, the neural network with 24 neurons and 2 hidden layers perform slightly better than the default one. In the end, which model to choose should depend on the practical goal and concerns.*